spring:
  datasource:
    url: jdbc:mysql://120.26.129.53:18233/bjobd?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&rewriteBatchedStatements=true&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: bjobd
    password: bjobd_317
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    sql-script-encoding: UTF-8
    hikari:
      pool-name: HikariCP
      connection-timeout: 60000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
      #leak-detection-threshold: 10000
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
      show-sql: true
        #hibernate:
      #ddl-auto: update
      #jackson:
      #default-property-inclusion: NON_EMPTY