server:
  port: 8080 #服务注册中心端口号
eureka:
  instance:
    hostname: 106.12.193.154 #服务注册中心IP地址
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://106.12.193.154:8081/eureka/
spring:
  application:
    name: eureka-server